# frozen_string_literal: true

module Rentvine
  OBJECT_TYPES = [
    [id: 1, name: 'Account'],
    [id: 2, name: 'User'],
    [id: 3, name: 'Contact'],
    [id: 4, name: 'Lease'],
    [id: 5, name: 'Bill'],
    [id: 6, name: 'Property'],
    [id: 7, name: 'Unit'],
    [id: 8, name: 'Deposit'],
    [id: 9, name: 'Accounting Transaction'],
    [id: 10, name: 'Accounting Transaction Entry'],
    [id: 11, name: 'Portfolio'],
    [id: 12, name: 'Payout'],
    [id: 13, name: 'Bank Adjustment'],
    [id: 14, name: 'Company'],
    [id: 15, name: 'Statement'],
    [id: 16, name: 'Work Order'],
    [id: 17, name: 'Inspection'],
    [id: 18, name: 'Inspection Area'],
    [id: 19, name: 'Inspection Item'],
    [id: 20, name: 'Application'],
    [id: 21, name: 'Applicant'],
    [id: 22, name: 'Bank Transfer'],
    [id: 23, name: 'Listing'],
    [id: 24, name: 'Appliance'],
    [id: 25, name: 'Text Message'],
    [id: 26, name: 'Email Message'],
    [id: 27, name: 'Work Order Estimate'],
    [id: 28, name: 'Settlement'],
    [id: 29, name: 'Lease Tenant'],
    [id: 30, name: 'Email Template'],
    [id: 31, name: 'Note'],
    [id: 32, name: 'File Attachment'],
    [id: 33, name: 'Vendor Bill'],
    [id: 34, name: 'Document Transaction'],
    [id: 35, name: 'Document Envelope'],
    [id: 36, name: 'Application Template'],
    [id: 37, name: 'Recurring Bill'],
    [id: 38, name: 'Chat Message'],
    [id: 39, name: 'Reconciliation'],
    [id: 40, name: 'Path'],
    [id: 41, name: 'Payout Return'],
    [id: 42, name: 'Management Fee Setting'],
    [id: 43, name: 'Additional Management Fee Setting'],
    [id: 44, name: 'Accounting Setting'],
    [id: 45, name: 'Posting Setting'],
    [id: 46, name: 'Late Fee Setting'],
    [id: 47, name: 'Statement Setting'],
    [id: 48, name: 'Payout Batch'],
    [id: 49, name: 'Letter'],
    [id: 50, name: 'Reminder'],
    [id: 51, name: 'Review']
  ].freeze
end
